'use client';

import { useEffect, useMemo, useRef, useState, type MouseEvent } from 'react';
import { calibrate, coverageMarkers, DEFAULTS, dots, dotStyle, HEIGHT, mapGeo, mapPixel, measurement, routeLength, toGeo, toLocal, validateSettings, WIDTH, type Geo, type Point, type Settings } from '../../lib/measurement/geometry';
import { exportData, overlaySvg } from '../../lib/measurement/export';
import styles from './tool.module.css';

type Mode = 'dots' | 'landmarks' | 'mask' | 'route';
const KEY='witness-measurement-v1';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Numeric({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(n:number)=>void;min:number;max:number;step?:number}) {return <label className={styles.field}>{label}<input type="number" value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!==''&&Number.isFinite(e.target.valueAsNumber))onChange(Math.max(min,Math.min(max,e.target.valueAsNumber)));}}/></label>;}
export default function MeasurementTool(){
 const [s,setS]=useState<Settings>(DEFAULTS),[loaded,setLoaded]=useState(false),[mode,setMode]=useState<Mode>('dots'),[pending,setPending]=useState<Point|null>(null),[draft,setDraft]=useState<Point[]>([]),[status,setStatus]=useState(''),[selected,setSelected]=useState<string|null>(null),[zoom,setZoom]=useState(19),[mapCentre,setMapCentre]=useState<Geo>(DEFAULTS.camera),[large,setLarge]=useState(false),[imageReady,setImageReady]=useState(false),[mapFailed,setMapFailed]=useState(false),[exporting,setExporting]=useState(false);
 const imageRef=useRef<HTMLImageElement>(null),importRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{let active=true;const image=imageRef.current;if(image)void image.decode().then(()=>{if(active)setImageReady(true);}).catch(()=>{if(active)setStatus('The source panorama failed to load. Reload to retry.');});return()=>{active=false;};},[]);
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const restored=validateSettings(JSON.parse(saved));setS(localStorage.getItem(`${KEY}-25px`)?restored:{...restored,spacing:25,excluded:[]});}localStorage.setItem(`${KEY}-25px`,'1');if(!localStorage.getItem(`${KEY}-coverage-v3`)){setS(previous=>({...previous,polygon:DEFAULTS.polygon,edgeGuides:DEFAULTS.edgeGuides,distantRoad:DEFAULTS.distantRoad,maxDistance:100}));localStorage.setItem(`${KEY}-coverage-v3`,'1');}}catch{setStatus('Saved settings could not be read. Using the starter mapping.');}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(KEY,JSON.stringify(s));}catch{setStatus('Browser storage is unavailable. Download JSON to save your work.');}},[s,loaded]);
 const calibration=useMemo(()=>calibrate(s),[s]),points=useMemo(()=>dots(s),[s]);
 const coverage=useMemo(()=>coverageMarkers(s),[s]);
 const dotAppearance=dotStyle(s.spacing);
 const current=points.find(p=>p.id===selected),fitGeo=toGeo(calibration.camera);
 const centre=mapPixel(mapCentre,zoom),offset={x:centre.x-300,y:centre.y-250};
 const mapPosition=(geo:Geo)=>{const p=mapPixel(geo,zoom);return {x:p.x-offset.x,y:p.y-offset.y};};
 const tiles=[];for(let y=Math.floor(offset.y/256);y<=Math.floor((offset.y+500)/256);y++)for(let x=Math.floor(offset.x/256);x<=Math.floor((offset.x+600)/256);x++)tiles.push({x,y});
 const patch=(part:Partial<Settings>)=>setS(prev=>({...prev,...part}));
 function imageClick(e:MouseEvent<SVGSVGElement>){const rect=e.currentTarget.getBoundingClientRect();const p={x:(e.clientX-rect.left)/rect.width*WIDTH,y:(e.clientY-rect.top)/rect.height*HEIGHT};
  if(mode==='mask'){setDraft(a=>[...a,p]);return;}
  if(!measurement(p,s,calibration)){setStatus('Choose a ground point below the horizon and within the distance limit.');return;}
  if(mode==='landmarks'){setPending(p);setStatus('Now click the same ground landmark on the satellite map.');return;}
  if(mode==='route'){patch({route:[...s.route,p]});return;}
  patch({manual:[...s.manual,p]});setSelected(`manual-${s.manual.length}`);setStatus('Dot added. Click an existing dot to inspect or remove it.');
 }
 function mapClick(e:MouseEvent<SVGSVGElement>){if(!pending||mode!=='landmarks')return;const rect=e.currentTarget.getBoundingClientRect();const geo=mapGeo({x:offset.x+(e.clientX-rect.left)/rect.width*600,y:offset.y+(e.clientY-rect.top)/rect.height*500},zoom);patch({landmarks:[...s.landmarks,{id:`L${Date.now()}`,name:`Ground landmark ${s.landmarks.length+1}`,image:pending,geo,check:s.landmarks.filter(l=>!l.check).length>=4}]});setPending(null);setStatus('Landmark saved. New points are held out as checks once four fit points exist.');}
 function removeDot(){if(!selected)return;if(selected.startsWith('manual-'))patch({manual:s.manual.filter((_,i)=>`manual-${i}`!==selected)});else patch({excluded:[...s.excluded,selected]});setSelected(null);}
 async function exportImage(transparent=false){setExporting(true);try{if(!imageReady||!imageRef.current)throw new Error('The source image has not loaded.');const canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');if(!transparent)ctx.drawImage(imageRef.current,0,0,WIDTH,HEIGHT);const url=URL.createObjectURL(new Blob([overlaySvg(s,!transparent)],{type:'image/svg+xml'}));try{const overlay=new Image();overlay.src=url;await overlay.decode();ctx.drawImage(overlay,0,0);}finally{URL.revokeObjectURL(url);}const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('Image export failed.');download(blob,transparent?'witness-distance-dots.png':'witness-distance-annotated.png');setStatus('Exported at 2048 × 920 pixels.');}catch(error){setStatus(error instanceof Error?error.message:'Export failed.');}finally{setExporting(false);}}
 function exportCSV(){const rows=[['id','texture_x','texture_y','export_x','export_y','horizontal_m','slant_m','latitude','longitude','method','status'].join(','),...points.map(p=>[p.id,p.textureX,p.textureY,p.x,p.y,p.distance,p.slantDistance,p.geo.lat,p.geo.lon,p.method,'provisional'].join(','))];download(new Blob([rows.join('\n')],{type:'text/csv'}),'witness-distances.csv');}
 const changeMode=(m:Mode)=>{setMode(m);setPending(null);setStatus('');};
 const supplied=toLocal(s.camera);
 const cameraShift=Math.hypot(calibration.camera.x-supplied.x,calibration.camera.y-supplied.y);
 return <main className={styles.workspace}>
  <header className={styles.header}><div><a href="/">WITNESS / Paris Garden</a><h1>Distance mapping</h1></div><div className={styles.actions}><span>{loaded?'Saved in this browser':'Loading settings…'}</span><button disabled={!imageReady||exporting} onClick={()=>void exportImage()} className={styles.primary}>{exporting?'Exporting…':'Download annotated image'}</button></div></header>
  <div className={styles.notice}><strong>Approximate ground distances.</strong> Starter landmarks are provisional. {calibration.fitted?`Map fit RMS ${calibration.fitRms?.toFixed(1)} m; leave-one-out error ${calibration.crossValidationRms?.toFixed(1)??'unavailable'} m.`:'No valid map fit yet.'} The 1–2 m target is not established. Teal labels (*) are rough far-road estimates using a locally adjusted horizon, not a validated map fit. Click objects at their ground contact.</div>
  <div className={styles.toolbar}><div className={styles.modes}>{(['dots','landmarks','mask','route'] as Mode[]).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>changeMode(m)}>{({dots:'Place dots',landmarks:'Match landmarks',mask:'Ground area',route:'Car route'})[m]}</button>)}</div><button onClick={()=>setLarge(!large)}>{large?'Fit image':'View at export size'}</button></div>
  <p className={styles.instruction}>{mode==='dots'?'Click the image to add a dot. Select a dot to inspect its distance. The automatic grid uses export pixels.':mode==='landmarks'?'Click a ground landmark in the photo, then its matching position on the map. Use check points to test the fit.':mode==='mask'?'Trace a new ground-only boundary. Avoid cars, walls and raised surfaces. Apply when the outline is complete.':'Click successive ground positions to draw the vehicle route. Distances follow your clicked path.'}</p>
  <section className={styles.imageScroll} aria-label="Panorama distance editor"><div className={styles.imageStage} style={large?{width:WIDTH}:undefined}>
   {/* Native image keeps image pixels and export coordinates identical. */}
   {/* eslint-disable-next-line @next/next/no-img-element */}
   <img ref={imageRef} src="/bastille-court-photosphere.jpg" alt="Panorama of Paris Garden outside Bastille Court" onLoad={()=>setImageReady(true)} onError={()=>setStatus('The source panorama failed to load. Reload to retry.')} />
   <svg viewBox={`0 0 ${WIDTH} ${HEIGHT}`} role="img" aria-label="Clickable ground distance dots" onClick={imageClick}>
    <defs><marker id="route-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#ffe082"/></marker></defs>
    {mode==='mask'&&<><polygon points={s.polygon.map(p=>`${p.x},${p.y}`).join(' ')} fill="#ffe08222" stroke="#ffe082" strokeWidth="2"/><polyline points={draft.map(p=>`${p.x},${p.y}`).join(' ')} fill="#9cded533" stroke="#9cded5" strokeWidth="3"/>{draft.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="6" fill="#9cded5"/>)}</>}
    <polyline points={s.route.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#ffe082" strokeWidth="4" markerMid="url(#route-arrow)" markerEnd="url(#route-arrow)"/>
    {coverage.map(p=><circle key={p.id} cx={p.x} cy={p.y} r="2.5" fill="none" stroke="#9cded5" strokeWidth="1.2"><title>Ground coverage only: distance unavailable</title></circle>)}
    {points.map(p=><g key={p.id} className={styles.dot} role="button" tabIndex={0} aria-label={`${p.id}, approximately ${p.distance.toFixed(1)} metres`} onClick={e=>{if(mode==='dots'){e.stopPropagation();setSelected(p.id);}}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(p.id);}}}><circle cx={p.x} cy={p.y} r={selected===p.id?dotAppearance.radius+3:dotAppearance.radius} fill={selected===p.id||p.lowConfidence?'#9cded5':'#ffe082'} stroke="#202c2b" strokeWidth="2"/><text x={p.x} y={p.y-dotAppearance.offset} textAnchor="middle" style={{fontSize:dotAppearance.fontSize,strokeWidth:dotAppearance.stroke}} textLength={dotAppearance.labelWidth} lengthAdjust="spacingAndGlyphs">≈{p.lowConfidence?Math.round(p.distance):p.distance.toFixed(1)} m{p.lowConfidence?'*':''}</text></g>)}
    {mode==='landmarks'&&s.landmarks.map((l,i)=><g key={l.id}><circle cx={l.image.x} cy={l.image.y} r="11" fill={l.check?'#9cded5':'#f7b8a0'}/><text x={l.image.x+16} y={l.image.y-12} className={styles.landmarkText}>{i+1}</text></g>)}
    {pending&&<circle cx={pending.x} cy={pending.y} r="15" stroke="#f7b8a0" strokeWidth="4" fill="none"/>}
   </svg>
  </div></section>
  <div className={styles.belowImage}><span>{points.length} distance dots + {coverage.length} coverage markers · {WIDTH} × {HEIGHT} export · {s.spacing} px spacing · horizontal distance</span>{mode==='mask'&&<div className={styles.actions}><button disabled={!draft.length} onClick={()=>setDraft(draft.slice(0,-1))}>Undo vertex</button><button disabled={draft.length<3} onClick={()=>{patch({polygon:draft,excluded:[],edgeGuides:[]});setDraft([]);changeMode('dots');}}>Apply ground area</button><button onClick={()=>{setDraft([]);patch({polygon:DEFAULTS.polygon,edgeGuides:DEFAULTS.edgeGuides,distantRoad:DEFAULTS.distantRoad,maxDistance:100});}}>Restore starter area</button></div>}{mode==='route'&&<div className={styles.actions}><span>Route: ≈{routeLength(s).toFixed(1)} m</span><button disabled={!s.route.length} onClick={()=>patch({route:s.route.slice(0,-1)})}>Undo route point</button><button disabled={!s.route.length} onClick={()=>patch({route:[]})}>Clear route</button></div>}</div>
  <div className={styles.detailGrid}>
   <section className={styles.mapSection}><div className={styles.sectionHeader}><h2>Match the ground</h2><div className={styles.actions}><button aria-label="Zoom map out" disabled={zoom<=17} onClick={()=>{setZoom(zoom-1);setMapFailed(false);}}>−</button><span>Zoom {zoom}</span><button aria-label="Zoom map in" disabled={zoom>=19} onClick={()=>{setZoom(zoom+1);setMapFailed(false);}}>+</button><button onClick={()=>setMapCentre(fitGeo)}>Centre on fitted camera</button></div></div>
   <div className={styles.map}><svg viewBox="0 0 600 500" onClick={mapClick} aria-label="Satellite map for matching landmarks" role="img">
    {tiles.map(t=><image key={`${zoom}-${t.x}-${t.y}`} href={`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${zoom}/${t.y}/${t.x}`} x={t.x*256-offset.x} y={t.y*256-offset.y} width="256" height="256" onError={()=>setMapFailed(true)}/>)}
    {points.map(p=>{const q=mapPosition(p.geo);return <circle key={p.id} cx={q.x} cy={q.y} r="2" fill="#ffe082"/>;})}
    <polyline points={s.route.flatMap(p=>{const m=measurement(p,s,calibration);if(!m)return [];const q=mapPosition(m.geo);return [`${q.x},${q.y}`];}).join(' ')} fill="none" stroke="#ffe082" strokeWidth="2"/>
    {s.landmarks.map((l,i)=>{const p=mapPosition(l.geo);return <g key={l.id}><circle cx={p.x} cy={p.y} r="9" fill={l.check?'#9cded5':'#f7b8a0'} stroke="#202c2b"/><text x={p.x} y={p.y+4} textAnchor="middle" fontSize="12" fill="#202c2b">{i+1}</text></g>;})}
    {[{g:s.camera,label:'Supplied GPS',colour:'#f7b8a0'},{g:fitGeo,label:'Fitted camera',colour:'#9cded5'}].map(({g,label,colour})=>{const p=mapPosition(g);return <g key={label}><path d={`M${p.x-9},${p.y}h18 M${p.x},${p.y-9}v18`} stroke={colour} strokeWidth="3"/><text x={p.x+12} y={p.y+5} fontSize="13" fill={colour} stroke="#202c2b" strokeWidth="3" paintOrder="stroke">{label}</text></g>;})}
   </svg><a className={styles.attribution} href="https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer" target="_blank" rel="noreferrer">Imagery © Esri, Maxar, Earthstar Geographics and GIS community</a></div>
   {mapFailed&&<p role="alert">Satellite tiles failed to load. Check your connection; you can still enter landmark coordinates below.</p>}
   <div className={styles.actions}>{[['West',-150,0],['North',0,-150],['South',0,150],['East',150,0]].map(([label,x,y])=><button key={label} onClick={()=>setMapCentre(mapGeo({x:centre.x+Number(x),y:centre.y+Number(y)},zoom))}>{label}</button>)}</div>
   <p>Use curb corners and ground markings. Roof edges are displaced by height. The starter alignment places the camera about {cameraShift.toFixed(1)} m from the supplied GPS; this remains an estimate.</p>
   </section>
   <section className={styles.settings}><h2>Distance & export</h2>
    <div className={styles.fields}><Numeric label="Dot spacing (export px)" value={s.spacing} min={25} max={300} step={25} onChange={spacing=>patch({spacing,excluded:[]})}/><Numeric label="Maximum distance (m)" value={s.maxDistance} min={2} max={100} onChange={maxDistance=>patch({maxDistance})}/><Numeric label="Horizon (export y)" value={s.horizon} min={400} max={600} onChange={horizon=>patch({horizon})}/><Numeric label="Initial heading (degrees)" value={s.heading} min={-360} max={360} onChange={heading=>patch({heading})}/><Numeric label="Fallback camera height (m)" value={s.height} min={.3} max={5} step={.05} onChange={height=>patch({height})}/>{s.distantRoad&&<Numeric label="Far-road horizon estimate (y)" value={s.distantRoad.horizon} min={400} max={520} onChange={horizon=>patch({distantRoad:{...s.distantRoad!,horizon}})}/>}</div>
    <p>The fit estimates camera position, heading offset and height ({calibration.height.toFixed(2)} m). Height input is used only without a valid landmark fit. Road slopes, raised pavement and panorama stitching can add error.</p>
    <dl className={styles.metrics}><div><dt>Fit residual</dt><dd>{calibration.fitRms?.toFixed(1)??'—'} m</dd></div><div><dt>Leave-one-out error</dt><dd>{calibration.crossValidationRms?.toFixed(1)??'—'} m</dd></div><div><dt>Held-out map checks</dt><dd>{calibration.checkRms===null?'Add check points':`${calibration.checkRms.toFixed(1)} m`}</dd></div></dl>
    {current&&<div className={styles.selection}><h3>Selected dot</h3><p>≈{current.distance.toFixed(1)} m along the ground · ≈{current.slantDistance.toFixed(1)} m line of sight</p><p>Source pixel {current.textureX.toFixed(0)}, {current.textureY.toFixed(0)}<br/>{current.geo.lat.toFixed(7)}, {current.geo.lon.toFixed(7)}</p><button onClick={removeDot}>Remove this dot</button></div>}
    <div className={styles.actions}><button disabled={!imageReady||exporting} onClick={()=>void exportImage(true)}>Dots-only PNG</button><button onClick={()=>download(new Blob([JSON.stringify(exportData(s),null,2)],{type:'application/json'}),'witness-mapping.json')}>Save mapping JSON</button><button onClick={exportCSV}>Distances CSV</button><button onClick={()=>importRef.current?.click()}>Import mapping</button></div>
    <input ref={importRef} type="file" accept="application/json,.json" hidden onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2_000_000)throw new Error('Mapping file is too large.');const data=JSON.parse(await f.text());setS(validateSettings(data.settings??data));setSelected(null);setPending(null);setDraft([]);setStatus('Mapping imported.');}catch(error){setStatus(error instanceof Error?error.message:'Could not import mapping.');}e.target.value='';}}/>
    <p>The annotated image and transparent dots use identical pixels. JSON also records original 9,216 × 4,140 source coordinates. Teal distance labels (*) flag rough distant estimates. Hollow dots mean no estimate is available. Edge markers follow the distant road more closely. Automatic dots are 25 px apart by default; hand-placed dots can be closer.</p>
    <details><summary>Camera GPS and reset</summary><div className={styles.fields}><Numeric label="Supplied latitude" value={s.camera.lat} min={-84} max={84} step={.0000001} onChange={lat=>patch({camera:{...s.camera,lat}})}/><Numeric label="Supplied longitude" value={s.camera.lon} min={-180} max={180} step={.0000001} onChange={lon=>patch({camera:{...s.camera,lon}})}/></div><button onClick={()=>{setS(structuredClone(DEFAULTS));setSelected(null);setPending(null);setDraft([]);setStatus('Restored provisional starter mapping.');}}>Reset to starter mapping</button></details>
   </section>
  </div>
  <section className={styles.landmarks}><div className={styles.sectionHeader}><h2>Landmark alignment</h2><button onClick={()=>changeMode('landmarks')}>Add landmark pair</button></div><p>Four fit points minimum. Add separate check points to evaluate accuracy. All starter matches are manual interpretations of imagery from a different date, so refine them before relying on measurements.</p><div className={styles.tableScroll}><table><thead><tr><th>Point / ground feature</th><th>Image x / y</th><th>Latitude / longitude</th><th>Use as check</th><th>Error</th><th>Remove</th></tr></thead><tbody>{s.landmarks.map((l,i)=><tr key={l.id}><td><label>{i+1}<input aria-label={`Landmark ${i+1} name`} value={l.name} onChange={e=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,name:e.target.value}:a)})}/></label></td><td><Numeric label={`Point ${i+1} image x`} value={l.image.x} min={0} max={WIDTH} onChange={x=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,image:{...a.image,x}}:a)})}/><Numeric label={`Point ${i+1} image y`} value={l.image.y} min={0} max={HEIGHT} onChange={y=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,image:{...a.image,y}}:a)})}/></td><td><Numeric label={`Point ${i+1} latitude`} value={l.geo.lat} min={-84} max={84} step={.0000001} onChange={lat=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,geo:{...a.geo,lat}}:a)})}/><Numeric label={`Point ${i+1} longitude`} value={l.geo.lon} min={-180} max={180} step={.0000001} onChange={lon=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,geo:{...a.geo,lon}}:a)})}/></td><td><input type="checkbox" aria-label={`Use landmark ${i+1} as a check`} checked={l.check} onChange={e=>patch({landmarks:s.landmarks.map(a=>a.id===l.id?{...a,check:e.target.checked}:a)})}/></td><td>{calibration.errors.find(a=>a.id===l.id)?.metres.toFixed(1)??'—'} m</td><td><button aria-label={`Remove landmark ${i+1}`} onClick={()=>patch({landmarks:s.landmarks.filter(a=>a.id!==l.id)})}>Remove</button></td></tr>)}</tbody></table></div></section>
  <footer className={styles.footer}><p role="status" aria-live="polite">{status||'Ready. Start with the provisional mapping, or refine its landmarks.'}</p><a href="/witness/distance-annotated.png" download>Download starter annotated image</a></footer>
 </main>;
}
