import { calibrate, coverageMarkers, dots, dotStyle, HEIGHT, WIDTH, routeLength, toGeo, type Settings } from './geometry.ts';
export function exportData(settings:Settings) {
 const calibration=calibrate(settings);
 return { schemaVersion:1, source:'/bastille-court-photosphere.jpg', image:{width:WIDTH,height:HEIGHT,sourceWidth:9216,sourceHeight:4140,fullSphereHeight:4608,cropTop:0}, metric:'horizontal ground distance from fitted camera; metres', status:'provisional map estimates; 1–2 m accuracy not established', settings, calibration:{...calibration,geo:toGeo(calibration.camera)}, dots:dots(settings), coverageMarkers:coverageMarkers(settings), routeLengthM:routeLength(settings) };
}
export function overlaySvg(settings:Settings, includeBanner=true) {
 const points=dots(settings);const coverage=coverageMarkers(settings);const c=calibrate(settings);const style=dotStyle(settings.spacing);
 const label = c.fitted ? `PROVISIONAL MAP ESTIMATES · fit RMS ${c.fitRms!.toFixed(1)} m · accuracy not established` : 'UNCALIBRATED · assumed camera height · accuracy not established';
 const route=settings.route.length>1?`<polyline points="${settings.route.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#ffd96a" stroke-width="4" marker-mid="url(#arrow)" marker-end="url(#arrow)"/>`:'';
 return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#ffd96a"/></marker></defs>${route}${coverage.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="2.5" fill="none" stroke="#9cded5" stroke-width="1.2"/>`).join('')}${points.map(p=>`<g><circle cx="${p.x}" cy="${p.y}" r="${style.radius}" fill="${p.lowConfidence?'#9cded5':'#ffe082'}" stroke="#202c2b" stroke-width="${Math.max(1,style.stroke/2)}"/><text x="${p.x}" y="${p.y-style.offset}" text-anchor="middle" fill="#fff8dd" stroke="#202c2b" stroke-width="${style.stroke}" paint-order="stroke" font-family="Arial,sans-serif" font-size="${style.fontSize}" ${style.labelWidth?`textLength="${style.labelWidth}" lengthAdjust="spacingAndGlyphs"`:""} font-weight="700">≈${p.lowConfidence?Math.round(p.distance):p.distance.toFixed(1)} m${p.lowConfidence?'*':''}</text></g>`).join('')}${includeBanner?`<rect width="${WIDTH}" height="66" fill="#202c2b" fill-opacity="0.94"/><text x="24" y="27" fill="#fff8dd" font-family="Arial,sans-serif" font-size="18">WITNESS / Camera distance · ${points.length} distances + ${coverage.length} coverage markers · ${settings.spacing} px grid · horizontal metres</text><text x="24" y="51" fill="#ffe082" font-family="Arial,sans-serif" font-size="16">${label} · * teal distances: rough far-road estimates; unvalidated</text>`:''}</svg>`;
}
