import test from 'node:test';
import assert from 'node:assert/strict';
import { calibrate, coverageMarkers, DEFAULTS, dots, groundRay, mapGeo, mapPixel, measurement, toGeo, toLocal, validateSettings, type Settings } from './geometry.ts';
import { exportData, overlaySvg } from './export.ts';
const close=(a:number,b:number,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
test('geographic and tile coordinates round trip',()=>{const g={lat:51.5056239,lon:-.1057864};const p=mapGeo(mapPixel(g,19),19);close(p.lat,g.lat);close(p.lon,g.lon);const q=toGeo(toLocal(g));close(q.lat,g.lat);close(q.lon,g.lon);});
test('cropped panorama horizon and nadir use full sphere height',()=>{assert.equal(groundRay({x:1024,y:512},512,94),null);const p=groundRay({x:1024,y:768},512,0)!;close(Math.hypot(p.x,p.y),1);const s={...DEFAULTS,landmarks:[],height:2};close(measurement({x:1024,y:768},s)!.distance,2);assert.equal(measurement({x:1024,y:400},s),null);});
test('recovers known camera position, height and orientation from independent pairs',()=>{const samples=[{x:200,y:650},{x:750,y:730},{x:1300,y:690},{x:1800,y:810},{x:950,y:590}];const a=1.7*Math.cos(.15),b=1.7*Math.sin(.15);const s:Settings={...DEFAULTS,landmarks:samples.map((image,i)=>{const p=groundRay(image,512,94)!;return{id:`${i}`,name:'synthetic',image,geo:toGeo({x:5+a*p.x-b*p.y,y:-3+b*p.x+a*p.y}),check:i===4};})};const fit=calibrate(s);assert.ok(fit.fitted);close(fit.camera.x,5);close(fit.camera.y,-3);close(fit.height,1.7);close(fit.checkRms!,0);close(fit.crossValidationRms!,0);});
test('check points never affect fitted camera and expose independent errors',()=>{const s=structuredClone(DEFAULTS);const before=calibrate(s);s.landmarks.push({...s.landmarks[0],id:'check',check:true,geo:toGeo({x:100,y:100})});const after=calibrate(s);close(before.camera.x,after.camera.x);assert.ok(after.checkRms!>50);});
test('degenerate landmarks fall back without NaN',()=>{const s={...DEFAULTS,landmarks:DEFAULTS.landmarks.map(l=>({...l,image:{x:850,y:606}}))};assert.equal(calibrate(s).fitted,false);assert.ok(dots(s).every(p=>Number.isFinite(p.distance)));});
test('grid has exact 25 px spacing, source coordinates and exclusions',()=>{const s=structuredClone(DEFAULTS);const p=dots(s);assert.ok(p.length>30);for(const d of p){if(d.id.startsWith('grid-')){close((d.x-12.5)%25,0);close((d.y-12.5)%25,0);}close(d.textureX,d.x*4.5);assert.ok(d.distance<=s.maxDistance);}s.excluded=[p[0].id];assert.equal(dots(s).length,p.length-1);});
test('unsafe imported settings are rejected',()=>{assert.throws(()=>validateSettings({...DEFAULTS,spacing:0}));assert.throws(()=>validateSettings({...DEFAULTS,camera:{lat:NaN,lon:0}}));assert.throws(()=>validateSettings({...DEFAULTS,landmarks:[...DEFAULTS.landmarks,DEFAULTS.landmarks[0]]}));assert.deepEqual(validateSettings(DEFAULTS),DEFAULTS);});
test('export image labels and mapping use identical dots',()=>{const data=exportData(DEFAULTS),svg=overlaySvg(DEFAULTS);assert.equal((svg.match(/<circle /g)||[]).length,data.dots.length+data.coverageMarkers.length);for(const d of data.dots)assert.ok(svg.includes(`≈${d.lowConfidence?Math.round(d.distance):d.distance.toFixed(1)} m`));assert.ok(svg.includes('accuracy not established'));});

test("distant labels identify local approximation and uncovered points stay unknown",()=>{const p=measurement({x:352,y:500},DEFAULTS)!;assert.ok(p.distance>30);assert.equal(p.method,'local-horizon-estimate');assert.ok(p.lowConfidence);assert.equal(measurement({x:352,y:490},{...DEFAULTS,distantRoad:undefined}),null);assert.ok(dots(DEFAULTS).some(p=>p.x>1450&&p.y<600));});
